### ISSUE TITLE
Why not output Y+C?

### ISSUE THREAD

**Issue by jotego** [MikeS11/MiSTerFPGA_YC_Encoder#5]
What is the reasoning behind leaving the addition of luminance and chrominance to the analog circuits outside the FPGA, rather than doing it inside the FPGA?

**Comment by MikeS11** [comment]
Hey Jotego! Alexey did try to create a CBVS output and you can try it, but there are hardware limitations. The main reason is the voltage output cap on any analog output to .7V where Chroma can sit at 0.850V, as well as needing to allow a larger bandwidth for chroma. E.g if I tried to fit the colorburst, chroma and luma into 1 output, you get a video output thats not remotely close to spec and it looks pretty bad.

**Comment by jotego** [comment]
I see, the limitation comes from the external DAC then. Thank you.
